export const categories = [
    { value: 'Rozrywka', label: 'Rozrywka' },
    { value: 'Elektronika', label: 'Elektronika' },
    { value: 'Moda', label: 'Moda' },
    { value: 'Dom/ogrod', label: 'Dom i ogród' },
    { value: 'Supermarket', label: 'Supermarket' },
    { value: 'Dziecko', label: 'Dziecko' },
    { value: 'Uroda', label: 'Uroda' },
    { value: 'Zdrowie', label: 'Zdrowie' },
    { value: 'Kultura/rozrywka', label: 'Kultura i rozrywka' },
    { value: 'Sport/turystyka', label: 'Sport i turystyka' },
    { value: 'Motoryzacja', label: 'Motoryzacja' },
    { value: 'Nieruchomosci', label: 'Nieruchomości' },
    { value: 'Kolekcje/sztuka', label: 'Kolekcje i sztuka' },
    { value: 'Firma/uslugi', label: 'Firma i usługi' },
    { value: 'Inne', label: 'Inne' },
    { value: 'Oddam', label: 'Oddam za darmo' },
]